#!/bin/bash

#while true; do
    coolant_info=$(sensors | awk '/Coolant/ {sub(/[0-9]$/, "", $3); gsub(/\+/, "", $3); $1=""; print $3; exit}')
    echo "󰏈 " "$coolant_info"
#    xsetroot -name "Coolant: $coolant_info"
#    sleep 5
#done

