#!/bin/bash

## to monitor my coolant temp

coolant_info=$(sensors | awk '/Coolant/ {sub(/[0-9]$/, "", $3); gsub(/\+/, "", $3); $1=""; print $3; exit}')
icon="󰏈 "
printf " %s %s \\n" "$icon" "$coolant_info"

