#!/bin/bash

#while true; do
    wflow_info=$(sensors | awk '/Flow/ && $3 !~ /^(1|2)$/ {printf "%1d.%1d\n", $3/10, $3%10}')
    echo "󰞍" "$wflow_info"
#    xsetroot -name "Coolant: $coolant_info"
#    sleep 5
#done

