import = [ "~/.config/alacritty/catppuccin-frappe.toml" ]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 15, y = 15 }
opacity = 0.95

[scrolling]
history = 1000
multiplier = 6

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
size = 22
